build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  LongParameterList:
    active: true
    functionThreshold: 11
    constructorThreshold: 11
    ignoreAnnotated:
      - Composable
      - Preview
  NestedBlockDepth:
    active: true
    threshold: 5
  ComplexCondition:
    active: false
  TooManyFunctions:
    active: false

style:
  UnusedPrivateMember:
    active: false
  UnusedParameter:
    active: true
  ReturnCount:
    active: true
    max: 10
  MaxLineLength:
    active: true
    maxLineLength: 240
    excludeCommentStatements: true
    excludeRawStrings: true
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  LoopWithTooManyJumpStatements:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Preview
      - Test
      - ParameterizedTest
  VariableNaming:
    active: false
  MatchingDeclarationName:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

potential-bugs:
  active: true
